아래 페이지의 테이블을 크롤링하여 pandas 데이터 프레임으로 만들어 주세요.
- https://www.premierleague.com/tables

In [5]:
from selenium import webdriver
import pandas as pd

In [6]:
# make dataframe 
columns = ["Position", "Club", "Played", "Won", "Drawn", "Lost", "GF", "GA", "GD", "Points"]
df = pd.DataFrame(columns=columns)

# open window
driver = webdriver.Chrome()
driver.get("https://www.premierleague.com/tables")

# close layer
try:
    driver.find_element_by_css_selector("#advertClose").click()
except:
    print("no layer")

# select teams
table = driver.find_elements_by_css_selector("#mainContent .tableBodyContainer")[0]
teams = table.find_elements_by_css_selector("tr:not(.expandable)")

# crawling data
for team in teams:
    data = {
        "Position": team.find_element_by_css_selector("td.pos").text,
        "Club": team.find_element_by_css_selector("td.team .long").text,
        "Played": team.find_element_by_css_selector("td:nth-child(4)").text,
        "Won": team.find_element_by_css_selector("td:nth-child(5)").text,
        "Drawn": team.find_element_by_css_selector("td:nth-child(6)").text,
        "Lost": team.find_element_by_css_selector("td:nth-child(7)").text,
        "GF": team.find_element_by_css_selector("td:nth-child(8)").text,
        "GA": team.find_element_by_css_selector("td:nth-child(9)").text,
        "GD": team.find_element_by_css_selector("td:nth-child(10)").text,
        "Points": team.find_element_by_css_selector("td:nth-child(11)").text
    }
    df.loc[len(df)] = data

# close driver
driver.close()

# save csv
df.to_csv("premierleague.csv", encoding="utf-8")

# display dataframe
df

no layer

,Position,Club,Played,Won,Drawn,Lost,GF,GA,GD,Points
0,1,Manchester City,27,23,3,1,79,20,+59,72
1,2,Manchester United,28,18,5,5,53,20,+33,59
2,3,Liverpool,28,16,9,3,65,32,+33,57
3,4,Tottenham Hotspur,28,16,7,5,53,24,+29,55
4,5,Chelsea,28,16,5,7,50,25,+25,53
5,6,Arsenal,27,13,6,8,51,36,+15,45
6,7,Burnley,28,9,10,9,22,25,-3,37
7,8,Leicester City,28,9,9,10,40,41,-1,36
8,9,Everton,28,9,7,12,32,47,-15,34
9,10,Watford,28,9,6,13,38,47,-9,33
10,11,Bournemouth,28,8,8,12,33,43,-10,32
11,12,Brighton and Hove Albion,28,7,10,11,26,37,-11,31
12,13,West Ham United,28,7,9,12,35,50,-15,30
13,14,Huddersfield Town,28,8,6,14,25,48,-23,30
14,15,Newcastle United,28,7,8,13,27,38,-11,29
15,16,Southampton,28,5,12,11,29,41,-12,27
16,17,Crystal Palace,28,6,9,13,25,43,-18,27
17,18,Swansea City,28,7,6,15,21,41,-20,27
18,19,Stoke City,28,6,8,14,28,54,-26,26
19,20,West Bromwich Albion,28,3,11,14,22,42,-20,20